# Generated by Django 2.0.4 on 2018-04-07 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('vaccines', models.BooleanField()),
                ('vaccines_obs', models.TextField()),
                ('maturation', models.BooleanField()),
                ('maturation_obs', models.TextField()),
                ('phisical_exam', models.BooleanField()),
                ('phisical_exam_obs', models.TextField()),
                ('pc', models.FloatField()),
                ('ppc', models.FloatField()),
                ('height', models.FloatField()),
                ('feeding', models.TextField()),
                ('observations', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
