# Generated by Django 2.0.4 on 2018-04-14 03:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcontrol',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='healthcontrol',
            name='user',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'pediatra'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
