# Generated by Django 2.0.3 on 2018-04-04 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('items_per_page', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('maintenance', models.BooleanField(default=False)),
            ],
        ),
    ]
