# Generated by Django 2.0.3 on 2018-04-04 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='address',
            field=models.CharField(default='Diagonal 114 329, La Plata, Buenos Aires', max_length=100),
        ),
        migrations.AddField(
            model_name='configuration',
            name='phone',
            field=models.CharField(default='0221 483-0171', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=models.TextField(default='El Hospital Gutierrez de La Plata fue inaugurado el 6 de Agosto de 1954. En ese entonces, el hospital funcionaba solo en el área central del edificio. En 1956, la casa de admisión Dardo Rocha es trasladada para dar lugar al Hogar Materno Infantil “Dra. Cecilia Grierson”, y posteriormente la Casa del Niño Alfredo Palacios. En 1972, el hospital es remodelado y pasa a tener 12 salas de internación y a 172 las camas de dotación. El ala ocupada por Casa del Niño es cedida al hospital en 1987, permitiendo el traslado de la Maternidad y servicio de Pediatría. Más tarde, en 1987, se inaugura el primer piso del ala derecha, contruido anteriormente ese mismo año, siendo ésta la última gran remodelación del hospital.'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='email',
            field=models.EmailField(default='info@hospitalgutierrez.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='items_per_page',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='title',
            field=models.CharField(default='Hospital Dr. Ricardo Gutiérrez', max_length=100),
        ),
    ]
