# Generated by Django 2.0.4 on 2018-04-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20180404_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='maintenance',
        ),
    ]
