# Generated by Django 2.0.3 on 2018-04-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDemographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridge', models.IntegerField()),
                ('heating', models.IntegerField()),
                ('electricity', models.IntegerField()),
                ('typeOfHousing', models.IntegerField()),
                ('pet', models.IntegerField()),
                ('typeOfWater', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.CharField(max_length=30)),
                ('documentType', models.IntegerField()),
                ('documentNumber', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('healthInsurance', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('dataDemographic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.DataDemographic')),
            ],
        ),
    ]
