# Generated by Django 2.0.3 on 2018-04-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20180403_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datademographic',
            name='electricity',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='datademographic',
            name='fridge',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='datademographic',
            name='pet',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15),
        ),
    ]
