# Generated by Django 2.0.3 on 2018-04-04 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20180403_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datademographic',
            name='heating',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Leña', 'Leña'), ('Electrica', 'Electrica')], max_length=25),
        ),
        migrations.AlterField(
            model_name='datademographic',
            name='typeOfHousing',
            field=models.CharField(choices=[('Material', 'Material'), ('Chapa', 'Chapa'), ('Madera', 'Madera')], max_length=25),
        ),
        migrations.AlterField(
            model_name='datademographic',
            name='typeOfWater',
            field=models.CharField(choices=[('Corriente', 'Corriente'), ('De Pozo', 'De Pozo')], max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='documentNumber',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(500000)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
